### ISSUE TITLE
Endless Sky not opening for Flatpak

### ISSUE THREAD

**Issue by uzumine** [endless-sky/endless-sky#11326]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Trying to open Endless Sky on Linux Mint would yield:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to find the resource directories!
```
I tried installing appimage and that didn't work either
May be the resource files for game is supposed to be placed in /usr/share/games/ ...
but I don't see anything there?

### Steps to Reproduce

1. Install Endless Sky via flatpak
2. Run it

### Expected Behavior

The game starts 

### Operating System

Linux Mint

### Game Source

GitHub Releases

### Game Version

0.10.12

**Comment by TomGoodIdea** [comment]
Looks like #11160; should be fixed in the next release. For now, if you want to use 10.12, you can download it from Github:
https://github.com/endless-sky/endless-sky/releases/download/v0.10.12/Endless_Sky-v0.10.12-x86_64.AppImage

**Comment by uzumine** [comment]
> For now, if you want to use 10.12, you can download it from Github: https://github.com/endless-sky/endless-sky/releases/download/v0.10.12/Endless_Sky-v0.10.12-x86_64.AppImage

Weirdly enough appimages doesn't work for me. Running it once with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) and absolutely nothing happen, intergrating it and you get an error:
` Failed to register AppImage in system via libappimag`

**Comment by TomGoodIdea** [comment]
> Weirdly enough appimages doesn't work for me

Is this a problem with our AppImage or AppImages in general?

> (I misclicked and closed this issue)

It's ok, I'd close this anyway as the bug has been fixed on master.

**Comment by uzumine** [comment]
> Is this a problem with our AppImage or AppImages in general?

Pretty sure its just the game's AppImage, my other AppImages work perfectly fine, and I don't think it's the Launcher's problem(?)

**Comment by vn971** [comment]
Can this be re-released on flatpak as a bugfix? Wanted to install this game for my girlfriend now, and it was a bit embarassing/sad that things just really didn't work. That is, the current official stable release is unusable at all without further tinkering. Even specifying --resources didn't help for me:

```
flatpak run io.github.endless_sky.endless_sky -- -r /var/lib/flatpak/app/io.github.endless_sky.endless_sky/current/active/files/share/games/endless-sky/data/

terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to find the resource directories!
```

**Comment by vn971** [comment]
@TheGiraffe3 Wow, thanks a lot for such a quick fix! I can't confirm right now, but I'll confirm a bit later

**Comment by vn971** [comment]
@TheGiraffe3 Somehow I'm still getting that error. Maybe I'm doing something wrong?:
```
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo 

flatpak install --user flathub io.github.endless_sky.endless_sky
Looking for matches…
Required runtime for io.github.endless_sky.endless_sky/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/23.08) found in remote flathub
Do you want to install it? [Y/n]: y

io.github.endless_sky.endless_sky permissions:
    ipc   fallback-x11   pulseaudio   wayland   x11   dri



        ID                                               Branch                 Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default              23.08                  i             flathub            169,2 MB / 169,6 MB
 2. [✓] org.freedesktop.Platform.GL.default              23.08-extra            i             flathub             23,7 MB / 169,6 MB
 3. [✓] org.freedesktop.Platform.Locale                  23.08                  i             flathub             17,9 kB / 372,2 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel             23.08                  i             flathub             13,4 MB / 13,6 MB
 5. [✓] org.freedesktop.Platform                         23.08                  i             flathub            179,6 MB / 230,7 MB
 6. [✓] io.github.endless_sky.endless_sky                stable                 i             flathub            362,8 MB / 376,5 MB

Installation complete.

flatpak run io.github.endless_sky.endless_sky
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to find the resource directories!
```

Maybe the fact that I'm using `flatpak --user` confuses Endless Sky?

**Comment by vn971** [comment]
I've also tried specifying `-r` now, but it didn't help:
```
flatpak run io.github.endless_sky.endless_sky -- -r ~/.local/share/flatpak/app/io.github.endless_sky.endless_sky/x86_64/stable/1d8e61323e084144f22fac44ab04f5cdcf4d3cf124954a6acfbb7be6f44307c5/files/share/games/endless-sky/data
```
(still gives the same error)

**Comment by TheGiraffe3** [comment]
It's possible that Flathub hasn't updated the repository yet. Do you mind trying in a few hours and see if it works then?

**Comment by vn971** [comment]
I've checked 11 pages of github issue for "--version" and didn't find anything like that, so I've created a new issue: https://github.com/endless-sky/endless-sky/issues/11398

**Comment by vn971** [comment]
I think I've just got an update through flatpak, but somehow the error is still present:
```
flatpak install -vvv --or-update --user flathub io.github.endless_sky.endless_sky
F: Opening user flatpak installation at path /home/vasya/.local/share/flatpak
Looking for matches…
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Fetching summary index file for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 10001 bytes
F: Loading https://dl.flathub.org/repo/summaries/13d3f5275a333026ba91e075fe279b8f04991ea70ce889a783af0b3ecab05d97.idx.sig using curl
F: Received 592 bytes
F: Fetching indexed summary delta aa12d16dac38d0f1993ccf58e9af0e3abe24c97b28502289ef7f955f19f319e0-037e304b44fffe42b509e71d418801bc036ea8b185269b5a8173dd280423f5bd.delta for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summaries/aa12d16dac38d0f1993ccf58e9af0e3abe24c97b28502289ef7f955f19f319e0-037e304b44fffe42b509e71d418801bc036ea8b185269b5a8173dd280423f5bd.delta using curl
F: Received 43835 bytes
F: Transaction: update flathub:app/io.github.endless_sky.endless_sky/x86_64/stable[*]
F: Looking for remote metadata updates for flathub
F: marking op update:app/io.github.endless_sky.endless_sky/x86_64/stable resolved to a185c923fcc3d92cfdbc657a303d59289f39306779a24cc094cc7e0b61a48f3b
F: Updating dependency org.freedesktop.Platform/x86_64/23.08 of io.github.endless_sky.endless_sky/x86_64/stable
F: Transaction: update flathub:runtime/org.freedesktop.Platform/x86_64/23.08[$old]
...
...
...
 1.	   	io.github.endless_sky.endless_sky	stable	u	flathub	< 376,5 MB

Proceed with these changes to the user installation? [Y/n]: y
Updating…
F: flatpak_dir_pull: Using commit a185c923fcc3d92cfdbc657a303d59289f39306779a24cc094cc7e0b61a48f3b for pull of ref app/io.github.endless_sky.endless_sky/x86_64/stable from remote flathub
Updating…                        0%  0 bytes/s
Updating… ████████████████████ 100%
...
...
...
Updates complete.
```

Then running:
```
flatpak run io.github.endless_sky.endless_sky 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to find the resource directories!
```

**Comment by vn971** [comment]
(Note again that the game is installed not system-wide but for this user only, via `flatpak --user`. Not sure if it's relevant.. maybe not.)

**Comment by warp-core** [comment]
Can further discussion of this go to an issue on the flathub repository, please?
It appears to be related to how the application is build and packaged by flathub, which is not within the scope of this repository.
