### ISSUE TITLE
Several landscape images have a red stripe on the left side

### ISSUE THREAD

**Issue by NickFleming501** [endless-sky/endless-sky#11638]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Several of the landscape images shown on planets appear to have a red stripe on the left edge of the image, one pixel wide. I first noticed this during regular play on Solace (in Pherkad), then decided to check the image files. As far as I can tell, the following landscape images are all affected by this (have a red stripe on the left edge):

- city23
- desert14
- desert15
- mountain27
- mountain28
- snow19
- snow21
- snow22
- snow23
- station4
- station6
- station8
- station9
- station10
- station13
- station17
- station18
- station21
- station23
- station26
- station30
- station32
- station35
- station36
- station37
- station40
- station41
- station42
- station43
- station44
- station45
- station46
- station47
- station48
- station49
- station50
- water12

While checking the images, I noticed that some images also have a wrong left edge, but not in red, instead appearing as if from another image:

- beach14
- canyon13
- lava12
- lava13
- sea19
- sea22
- sky10
- sky11
- snow17

### Steps to Reproduce

1. Land on e.g. Solace (in Pherkad), Heartvalley (in Io Lowe), Asterus (in Nocte), Muninn Station (in Zosma), or a different affected planet/station
2. Look at the landscape image
3. Notice the red stripe on the left edge

### Expected Behavior

Not having the red stripe on the left edge.

### Screenshots

Examples of the red stripe:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/bb17c0c3-8a62-42f8-87b0-bc49645fcbeb" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/03ab2f37-abb1-4024-9e45-185f8575935c" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/45cab589-0d7f-4c67-ac49-7086989fb8f9" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/94a7aa8c-32e6-4189-b5d8-15d542007a90" />

Example of the not-red stripe (left edge):

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1a13dd47-96cb-41f0-9c41-0661c7a691bf" />

### Link to save file

Should work with any file.

### Operating System

Debian 12

### Game Source

Steam

### Game Version

v0.10.14

### Additional Information

Looking on Github, it looks like all affected images are related to #11528, although not all images from that PR are affected.

**Comment by Anarchist2** [comment]
Addressed by #11617.

**Comment by NickFleming501** [comment]
Oh, I missed that there's already a PR for this. Looking at it though, it appears that there are some images with red edge that are not yet addressed by it:

- station13
- station23
- station26
- station42
- station46
- station48

Also, the images with the not-red edge that looks like it is from another image, are not fixed by it either.

**Comment by TomGoodIdea** [comment]
Isn't #11624 more complete than #11617?

**Comment by NickFleming501** [comment]
#11624 addresses all the images I found, and some more.
