### ISSUE TITLE
Check OpenGL version and print a clear error message

### ISSUE THREAD

**Issue by apathy-dude** [endless-sky/endless-sky#14]
Launching the game through both the PPA and building from source causes the following error:

`#version 120`
`uniform vec2 scale;`
`uniform vec2 position;`
`uniform int glyph;`
`in vec2 vert;`
`in vec2 corner;`
`out vec2 texCoord;`
`void main() {`
`  texCoord = vec2((glyph + corner.x) / 96.f, corner.y);`
`  gl_Position = vec4((vert + position) * scale, 0, 1);`
`}`
`0(7) : error C5060: out can't be used with non-varying texCoord`
`Shader compilation failed.`
`terminate called without an active exception`
`Aborted (core dumped)`

Relevant hardware: 
* Intel i7 920
* GeForce GTX 650 Ti Boost

OS: Linux 3.13.0-49-generic #83-Ubuntu x86_64

**Comment by apathy-dude** [comment]
Work around by switching to proprietary drivers instead of using Nouveau drivers.

**Comment by endless-sky** [comment]
Yes, the game requires at least OpenGL 3.0, which is GLSL version 1.30. That message is saying your Nouveau drivers only support GLSL 1.20, which is OpenGL 2.1.

I will modify the program to check your OpenGL version on start-up and to print a clearer and more informative error message. And, I'll make sure the next release includes a note that OpenGL 3.0 is needed. Sorry about that!

**Comment by apathy-dude** [comment]
Thanks for letting me know. I've renamed the issue to be better describe course of action.

**Comment by endless-sky** [comment]
Fixed in 822adca. Can you try switching back to the Nouveau drivers and verify that you receive a more helpful warning message in the terminal?

**Comment by apathy-dude** [comment]
When running with Nouveau from terminal I get:
`Endless Sky requires OpenGL version 3.0 or higher.`
`Your OpenGL version is 2.1.2 NVIDIA 304.125, GLSL version 1.20 NVIDIA via Cg compiler.`
`Please update your graphics drivers.`
`terminate called without an active exception`
`Aborted (core dumped)`

When running with Nouveau and double clicking the executable I get no error message and it just crashes.

**Comment by endless-sky** [comment]
It looks like I had not been quitting OpenAL properly, so it was crashing when the program quits. See if this is fixed in 896ce68.

**Comment by apathy-dude** [comment]
The message is now as follows:
`Endless Sky requires OpenGL version 3.0 or higher.`
`Your OpenGL version is 2.1.2 NVIDIA 304.125, GLSL version 1.20 NVIDIA via Cg compiler.`
`Please update your graphics drivers.`

When double clicking the executable I still get no error message just a crash. Which I'm assuming is intended since you're only piping to cerr.

**Comment by endless-sky** [comment]
I've modified the code to quit cleanly after printing that error message, instead of crashing (f534be9). Also, the error message should now be displayed in a message box in addition to the terminal, so it will be visible even if you launched the program by double-clicking it.

**Comment by apathy-dude** [comment]
The message is now the same in console and in the message box.

This issue seems resolved, I'd close the ticket but I'm not sure if you're waiting to do an official tag before you close it or something.
