### ISSUE TITLE
A few uninhabited Saryd worlds offer hiring crew

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2515]
Ceaseless Toil, Diligent Hand, Mystery, and Revelation are the ones I've seen so far. The former two are factory worlds run by robots and the latter two are uninhabited moons. I believe that these planets should have the `uninhabited` attribute, as they have no spaceports either.

**Comment by tehhowch** [comment]
the `uninhabited` attribute is pretty rarely used in the description of planets (Hope and Far'en Lai are the only cases), #2449 would add it to Watcher. 

It is strange that you are able to interact with the Bank, Trade, Crew, etc. on worlds described as solely populated with robots that manage factory planning, construction, and operations. This may be better resolved by implementing @jmhorjus #951 solution of the `no banking`, etc tags, as these Saryd worlds (and others) are not exactly "uninhabited", even though they lack spaceports.

**Comment by jmhorjus** [comment]
Thanks for the shout-out. It's been a while...but I guess I still get notified when people say my name around here. :)
@tehhowch Consider the fate of #951 before sinking your time into similar endeavors.

**Comment by Amazinite** [comment]
Mereti stations also allow you to hire crew. Not sure if that one is intentional.

**Comment by tehhowch** [comment]
All easily solved with #2543 and "no crew" as a planet attribute.

**Comment by Amazinite** [comment]
The PR exists for this issue. Closing.
